import './globals.css'
import { Rubik } from 'next/font/google'
import AuthContextProvider from './(context)/AuthContext.js'
import Navbar from './(components)/Navbar.jsx'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <AuthContextProvider>
          <Navbar/>
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
